name: mirasimages
favicon: null
layout_spectrum: 1
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#221817'
    - '#382320'
    - '#4f2f24'
    - '#7b4328'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
